import type { Metadata } from "next";
import { Inter, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Providers from "./providers/providers";
const inter = Inter({ subsets: ["latin"] });
const cormorantGaramond = Cormorant_Garamond({
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter, cormorantGaramond)}>
        {" "}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
